### ISSUE TITLE
Accuracy concerns?

### ISSUE THREAD

**Issue by okeyes-r7** [natano/python-entropy#2]
Using tools like http://www.shannonentropy.netmark.pl/calculate I get very different outcomes than from with this module; that provides 0.9183 for "foo", for example, whereas entropy.shannon_entropy provides 0.11478697512328288 . Am I using it incorrectly?

**Comment by natano** [comment]
The tool you link to seems to calculate the entropy of english text, with the set of symbols being {a, b, ..., z} and taking the probability of single letters into account. In contrast the purpose of the python-entropy package is to analyze arbitrary binary data (symbols={0, 1, ..., 255}) without having knowledge of the characteristics of the content thereof. The result of the entropy calculation formula depends heavily on the set of symbols used and the probabilities assigned to each symbol. Thus the differing results. I suggest reading [Shannon's paper](http://www.eecs.berkeley.edu/~christos/classics/shannon-report.pdf), which explains the matter in much more detail and much more eloquently than I can reproduce here.

**Comment by Ironholds** [comment]
Fair. However, http://pythonfiddle.com/shannon-entropy-calculation/ reads (at least to my eye) as analysing the binary data - it's looking at the bytecodes, similarly - and produces totally different results.

Like, I want to be clear that this wasn't just a one-off comparison (I should've written the opening comment in a more expanded way): there's a massive amount of disagreement in outcome between different tools, and this is the only tool I can find that doesn't agree with *any* of the others, even when it appears (to my eye) the C is doing something very similar to the Python, and I'm wondering what I'm missing.
